version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

    commands:
        # install dependency
        - npm install

  build:
     commands:
         - npm run-script build
artifacts:
  # include  all the files required to run application
  files:
    -  '**/*'
